# Generated by Django 5.0 on 2024-06-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Imagen', models.ImageField(default='audif1.jpeg', upload_to='images/')),
            ],
        ),
    ]
